apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adguard-home.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adguard-home.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "adguard-home.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: adguard-home-config
        configMap:
          name: {{ printf "%s-%s" .Release.Name "config"  }}
      - name: data-vol
        emptyDir:
          sizeLimit: 500Mi
      - name: config-dir
        emptyDir:
          sizeLimit: 500Mi
      {{- if .Values.config.tls.enabled }}
      - name: tls-cert
        secret:
          defaultMode: 420
          secretName: "{{ .Values.ingress.tls.secretName }}"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf && sleep 10 && /opt/adguardhome/AdGuardHome --no-check-update --config /opt/adguardhome/conf/AdGuardHome.yaml
          ports:
          - name: dns-tcp
            containerPort: 53
            protocol: TCP
          - name: dns-udp
            containerPort: 53
            protocol: UDP
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
          - name: https-udp
            containerPort: 443
            protocol: UDP
          - name: dns-over-tls
            containerPort: 853
            protocol: TCP
          - name: dns-over-quic-1
            containerPort: 784
            protocol: UDP
          - name: dns-over-quic-2
            containerPort: 853
            protocol: UDP
          - name: dns-over-quic-3
            containerPort: 8853
            protocol: UDP
          - name: dnscrypt
            containerPort: 5443
            protocol: TCP
          - name: dnscrypt-udp
            containerPort: 5443
            protocol: UDP
          livenessProbe:
            httpGet:
              path: /login.html
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /login.html
              port: http
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: data-vol
            mountPath: /opt/adguardhome/work
            subPath: work
          - name: data-vol
            mountPath: /opt/adguardhome/conf
            subPath: conf
          - mountPath: /tmp
            name: adguard-home-config
          {{- if .Values.config.tls.enabled }}
          - mountPath: /opt/adguardhome/certificates
            name: tls-cert
          {{- end }}
