{{- if .Values.app.nginx.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nginx-configmap
data:
  wger-app.conf: |
    # custom access log configuration
    log_format custom '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # proxy
    upstream app_server {
      # fail_timeout=0 means we always retry an upstream even if it failed
      # to return a good HTTP response <- according to gunicorn doc
      server 127.0.0.1:8000 fail_timeout=0;
      zone upstreams 64K;
      keepalive 2;
    }

    # if no Host match, close the connection to prevent host spoofing
    server {
      listen 80 default_server;
      return 444;
    }

    # webserver
    server {
      listen 8080 deferred;
      client_max_body_size 4G;

      # set the correct host(s) for your site
      server_name {{ join " " .Values.ingress.url }};

      access_log /var/log/nginx/access.log custom;
      error_log  /var/log/nginx/error.log warn;

      # path for static files (only needed for serving "local" static and media files)
      root /var/www/html/;

      location / {
        # checks for static file, if not found proxy to app
        try_files $uri @proxy_to_app;
      }

      location @proxy_to_app {
        proxy_http_version 1.1;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        {{- if .Values.ingress.tls }}
        proxy_set_header X-Forwarded-Proto https;
        {{- else }}
        proxy_set_header X-Forwarded-Proto $scheme;
        {{- end }}
        proxy_set_header Host $http_host;

        # keep alive
        proxy_set_header   "Connection" "";

        # https://www.getpagespeed.com/server-setup/nginx/tuning-proxy_buffer_size-in-nginx
        proxy_buffer_size 32k;
        proxy_busy_buffers_size 40k; # proxy_buffer_size + 2 small buffers of 4k
        proxy_buffers 64 4k;
        proxy_max_temp_file_size 0;

        # give gunicorn time to process
        proxy_read_timeout 1800;

        proxy_redirect off;
        proxy_pass http://app_server;
      }
    }
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: wger-pg-init
data:
  40-grantSuperuser.sql: |
    ALTER USER {{ .Values.postgres.userDatabase.user.value }} WITH SUPERUSER;
