{{- if .Values.redis.enabled }}
{{- if .Values.redis.auth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.redis.auth.password }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{ else }}
  {{- if .Release.IsUpgrade }}
  redis-password: {{ index (lookup "v1" "Secret" .Release.Namespace "redis").data "redis-password" | quote }}
  {{ else }}
  redis-password: {{ randAlphaNum 25 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
