---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.jwt.secret.name | default "jwt" }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{ if .Values.app.jwt.secret.key }}
  signing-key: {{ .Values.app.jwt.secret.key | quote }}
  {{ else }}
  signing-key: {{ randAlphaNum 50 | quote }}
  {{ end }}
