---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-http
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{.Release.Name}}
  {{- with .Values.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote}}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      {{- if .Values.app.nginx.enabled }}
      targetPort: 8080
      {{- else }}
      targetPort: 8000
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-app
