{{- if .Values.recipes.externalDatabase.enabled }}
{{- if not .Values.recipes.externalDatabase.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "recipes.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ default "" .Values.recipes.externalDatabase.password | b64enc | quote }}
  db-username: {{ default "" .Values.recipes.externalDatabase.user | b64enc | quote }}
{{- end }}
{{- end }}