{{- if and (eq .Values.persistence.existingPvcName "") (.Values.persistence.enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "linkding.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}