---
apiVersion: v2
version: 0.0.1
appVersion: latest
name: wger
description: A Helm chart for Wger installation on Kubernetes
type: application
maintainers:
  - name: rolandgeider
    email: roland@geider.net
  - name: bbkz
dependencies:
  - name: postgres
    condition: postgres.enabled
    tags:
      - groundhog2k
    version: 1.3.1
    repository: https://groundhog2k.github.io/helm-charts
  - name: redis
    condition: redis.enabled
    tags:
      - groundhog2k
    version: 1.2.0
    repository: https://groundhog2k.github.io/helm-charts
