name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add meilisearch https://meilisearch.github.io/meilisearch-kubernetes

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"